This fork was cloned from http://github.com/dmgerman/xournal

dmgerman added egg_find_toolbar to the original xournal that allows search. it would jump to the next page in the pdf that contains the word in the search field

** USE AT YOUR OWN RISK!!!!!!!!!!!!!

** this code currently compiles and "works for me" by running =make=. OSX 10.6.4, gcc i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1
  - i installed the deps with MacPorts ( =sudo port install xournal= ), and replace the MacPorts xournal

** current commit contains these modifications:

*** highlight search results
  - clicking "Find next" in the search bar will highlight matches. again, the search begins on the NEXT page.
    - so if you are looking for something on the current page, either scroll backwards, or you have to wrap around
  - it only displays highlights in the current page of the search. if you scroll to any other page, there will be no highlights
  - the highlights are destroyed when you jump to the next page
  - *if you want to remove the highlight your only choice then is to search for an inexistent string*
  - the highlights are stored in a global variable =searchLayer=
  - search for =0xffff0080= in xo-callbacks.c to change the highlight color

*** select text & copy to clipboard
  - basically copy pasta of the SelectRectangle code, but in =finalize_selecttext=, call =poppler_page_get_text= on the rect region
  - choose the "Select Text" tool (next to select tool), or press =Ctrl-/=
  - draw a rectangle over the area you want to select+copy
  - after you release, it will attempt to find the text inside and copy to clipboard *immediately*
  - i tested this, it is not very reliable, but it does the job for me
  - search for =0x40409040= in xo-paint.c (in =start_selecttext=) to change select box color

** current issues with the "search" and "copy text" function
  - I'm not confident about the freeing memory part in the highlighting matches functions ( =find_pdf_matches= )
  - "Previous match" in the search toolbar causes segfault
  - i hope to modify the search behavior so it begins search on the current page
  - the "dodraw" flag hack was a crappy attempt at this. find it in the =find_pdf_matches= function; not going to last
  - probably =poppler_page_get_text= behavior -- if somehow your rectangle doesn't get stuff it seems to return a large block of text. i don't know exactly what it does... i just retry my selection. better than having to open Preview!
  - i also get "failed assertion of point != NULL" or something of that sort

** errata (probably should go somewhere else)

    if you are interested in editing .xoj in vim, add these lines to your vimrc (requires gzip support):

#+begin_src
autocmd BufReadPre,FileReadPre    *.xoj setlocal bin
autocmd BufReadPost,FileReadPost  *.xoj  call gzip#read("gzip -S .xoj -dn")
autocmd BufWritePost,FileWritePost    *.xoj  call gzip#write("gzip -S .xoj")
autocmd FileAppendPre         *.xoj  call gzip#appre("gzip -S .xoj -dn")
autocmd FileAppendPost      *.xoj  call gzip#write("gzip -S .xoj")
#+end_src


** fork me! xournal is great.

Version 0.4.5 (October 2, 2009)

Installation:   see INSTALL
Latest changes: see ChangeLog
User's manual:  see html-doc/manual.html
Updates:        see http://xournal.sourceforge.net/

See also: http://sourceforge.net/projects/xournal
