* xournal

is currently the *only* open source note-taking software that has top-notch annotation facilities for pdfs (and images), that works on Windows, Mac, and Linux. It is the default pdf reader on all my machines. I have tried Skim (Mac), Okular (Lin/Win/Mac), and a few others. Nothing comes close in interop, customizability, and features. Plus, your notes are stored in xoj files that are simple to edit and save and sync.

** USE AT YOUR OWN RISK.

- compiles & works for me on ubuntu 10.10
- OSX 10.6.4, 10.5.8: install deps with MacPorts ( =sudo port install xournal= ), and replace the MacPorts xournal

** contains these modifications:

*** from dmgerman (http://github.com/dmgerman/xournal)

contains egg_find_toolbar, allows search. jumps to the next page in the pdf that contains the word in the search field

*** highlight search results
  - clicking "Find next" in the search bar will highlight matches. again, the search begins on the NEXT page.
    - so if you are looking for something on the current page, either scroll backwards, or you have to wrap around
  - it only displays highlights in the current page of the search. if you scroll to any other page, there will be no highlights
  - the highlights are destroyed when you jump to the next page
  - *if you want to remove the highlight your only choice then is to search for an inexistent string*
  - the highlights are stored in a global variable =searchLayer=
  - search for =0xffff0080= in xo-callbacks.c to change the highlight color

*** select text & copy to clipboard
  - 2011-01-31 changed selectRect code (swap y1 & y2), somehow this makes selection more correct
  - rectanglular select tool, using SelectRectangle code, but in =finalize_selecttext=, call =poppler_page_get_text= on the rect region
  - popup dialog after select to confirm copy to clipboard
  - rectangular selection is not actually rectangular. it wraps around
  - search for =0x40409040= in xo-paint.c (in =start_selecttext=) to change select box color

** current issues with the "search" and "copy text" function
  - I'm not confident about the freeing memory part in the highlighting matches functions ( =find_pdf_matches= )
  - "Previous match" in the search toolbar causes segfault
  - i hope to modify the search behavior so it begins search on the current page
  - the "dodraw" flag hack was a crappy attempt at this. find it in the =find_pdf_matches= function; not going to last
  - probably =poppler_page_get_text= behavior -- if somehow your rectangle doesn't get stuff it seems to return a large block of text. i don't know exactly what it does... i just retry my selection. better than having to open Preview!
  - i also get "failed assertion of point != NULL" or something of that sort

** errata (probably should go somewhere else)

    if you are interested in editing .xoj in vim, add these lines to your vimrc (requires gzip support):

#+begin_src
autocmd BufReadPre,FileReadPre    *.xoj setlocal bin
autocmd BufReadPost,FileReadPost  *.xoj  call gzip#read("gzip -S .xoj -dn")
autocmd BufWritePost,FileWritePost    *.xoj  call gzip#write("gzip -S .xoj")
autocmd FileAppendPre         *.xoj  call gzip#appre("gzip -S .xoj -dn")
autocmd FileAppendPost      *.xoj  call gzip#write("gzip -S .xoj")
#+end_src


** wishlist/todo

   - complex "set as default"
     - always start highlighter with shape recognizer
   - set shape recognizer sensitivity
   - allow 3rd party paper options
     - sheet music
   - hold space to pan with mouse
   - text-awareness
     - text select
     - text highlighter
   - pretty pretty icon
   - investigate multitouch support

last update <2011-01-31 Mon 01:06>

** other update list
- 2011-01-31 safe pdf backgrounds with relative filepath if same basepath found
