* xournal

is currently the *only* open source note-taking software that has top-notch annotation facilities for pdfs (and images), that works on Windows, Mac, and Linux. It is the default pdf reader on all my machines. I have tried Skim (Mac), Okular (Lin/Win/Mac), and a few others. Nothing comes close in interop, customizability, and features. Plus, your notes are stored in xoj files that are simple to edit and save and sync.

** current status:

- compiles & works for me on ubuntu 12.04. uses poppler 18 that breaks previous code. my last working version for poppler 16 on ubuntu 11.04 is tagged =pre-poppler-19=.
- some iterations before that should work with OSX 10.6.4, 10.5.8. install deps with MacPorts ( =sudo port install xournal= ), and replace the MacPorts xournal. as of 2011-02 untested and you'll need some extra libraries
- libgcrypt11-dev + libsqlite3 for bookmark function

** contains these modifications:

*** select text, create a highlight box & copy selection to clipboard
    - popup dialog after select to confirm copy to clipboard
    - search for =0x40409040= in xo-paint.c (in =start_selecttext=) to change select box color

*** auto save and load last opened page
    when you open a pdf, xournal will jump to the last viewed page (unless overridden with dmgerman's page number command line argument). requires =sqlite3-dev= and =libgcrypt11-dev=. stores and reads ~/.xournal/xournal.db

** manually editing .xoj files

   if you are interested in editing .xoj in vim, add these lines to your vimrc (requires gzip support):

#+begin_example
  autocmd BufReadPre,FileReadPre    *.xoj setlocal bin
  autocmd BufReadPost,FileReadPost  *.xoj  call gzip#read("gzip -S .xoj -dn")
  autocmd BufWritePost,FileWritePost    *.xoj  call gzip#write("gzip -S .xoj")
  autocmd FileAppendPre         *.xoj  call gzip#appre("gzip -S .xoj -dn")
  autocmd FileAppendPost      *.xoj  call gzip#write("gzip -S .xoj")
#+end_example

** other update list
- 2011-01-31 safe pdf backgrounds with relative filepath if same basepath found
- 2011-02-01 added image extraction. copy to clipboard after text selection will now automatically save a png of the selected region; the png filename is written to ~/.xournal/extract.log for hook use
- 2011-02-01 executes the file found at =~/.xournal/hook-post-extract= if it exists
- 2011-02-05 actually create an undoable rectangle item where text-selection was used; mostly copy pasta from the stroke
- 2011-04-07 added files and modifications for nautilus thumbnail support by russell sears
- 2011-04-09 adding auto-bookmark and restore last-read page function

** more generalized changelog
  - 2011-01-31 changed selectRect code (swap y1 & y2), somehow this makes selection more correct
  - 2011-02-05 looks like it segfaults if there isn't a background pdf?
